{% set version = '1.0' %}

package:
  name: scitools
  version: {{version}}

source:
  git_url: git://github.com/neok-m4700/scitools.git
  git_tag: master

build:
  number: 99
  script: python setup.py install
  script_env:
    - DISPLAY # for testing

requirements:
  build:
    - {{GCC_R}} {{GCC_V|majmin}}
    - python {{PY_V|majmin}}
    - numpy {{NPY_V|majmin}}
  run:
    - lib{{GCC_R}} {{GCC_V|majmin}}
    - python {{PY_V|majmin}}
    - numpy {{NPY_V|majmin}}
    # runtime
    - tk
    - scipy
    - qtpy
    - matplotlib {{MPL_V|majmin}}
    - vtk
    - numba

test:
  files:
    - tester.py

about:
  home: hplgit.github.io/scitools/doc/web/index.html
  license: new BSD license
  summary: 'SciTools is a Python package containing many useful tools for scientific computing in Python'
